version: '3'
services:
  web:
    build: nginxlocal
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    build: dash_app
    volumes:
      - .:/dash_app
    expose:
      - 8050
